using System;
using System.Numerics;
using Thread = System.Threading.Thread;
using OpenFPS.Common;
using OpenFPS.Common.Components;
using OpenFPS.Client.AudioEngine.Data;
using OpenFPS.Client.AudioEngine.Fmod;

namespace OpenFPS.Client.Core.AudioEngine.Fmod;

/// <summary>
/// Verifies the ROUTING of a region's reverb through the real <see cref="FmodAudioProvider"/>, headless.
///
/// The live session reported that a siren inside a concrete room was heard with "the wash all around me,
/// not representative of the walls it is bouncing off of", and the graph explained it exactly. A region
/// bus was built as: reverb at the chain HEAD (the OUTPUT end), the doorway HRTF stage at the TAIL (the
/// INPUT end), and every source's send injected with `bus.getDSP(HEAD)` — that is, straight into the
/// reverb. FMOD's chain runs tail to head, so that send arrived DOWNSTREAM of both the bus fader and the
/// binaural stage. Three things followed, none of them visible from outside the mixer:
///   * `bus.setVolume` — the per-portal aperture/distance gating — applied to nothing, so a room's
///     reverb played at full level from anywhere on the map;
///   * the HRTF stage binauralized silence, so the reverb had no direction at all;
///   * SFXREVERB's dry path (0 dB) added an undirected copy of the source on top.
///
/// So the check is about the graph, and it needs a real one: the reverb tail is generated by FMOD, the
/// localization by Steam Audio's HRTF, and neither exists in a unit test. PASS requires all four:
///   1. Outside, off to one side: the bus's HRTF stage is ENGAGED and its two ears differ — the reverb
///      is arriving from the doorway rather than from everywhere.
///   2. Mirroring the listener to the other side of the doorway flips which ear leads.
///   3. Inside the room: the HRTF stage is BYPASSED — reverb fills the space rather than pointing at a
///      door the listener is standing in.
///   4. The gating is connected: the bus level falls off with distance from the doorway.
/// </summary>
public static class ReverbRouteSpike
{
    private const int RoomRegionId = 10;
    private static readonly Vector3 RoomCentre = new(-7f, 2f, 15f);
    private static readonly Vector3 Doorway = new(-7f, 1f, 10f);

    public static int Run()
    {
        AcousticRegistry.Initialize();

        var provider = new FmodAudioProvider();
        if (!provider.Initialize()) { Console.WriteLine("FAIL: provider init failed."); return 1; }

        try
        {
            provider.SetAcousticMap(BuildMap());

            // A continuous synth source standing in the middle of the room, like the map's siren.
            var siren = new SpatialEmitter
            {
                EntityId = 1,
                Type = EmitterType.WorldLocked,
                IsSynth = true,
                SynthWave = SynthWaveType.Noise,
                SynthFrequency = 220f,
                SynthFilterCutoff = 1.0f,
                Volume = 1.0f,
                Position = RoomCentre with { Y = 1.5f },
                Range = 60f,
                MinDistance = 2f,
                EnableReverb = true,
                TargetRegionId = RoomRegionId
            };
            provider.PlaySpatialSound(siren);

            // 1 + 4. Outside, well to the WEST of the doorway and a stride back from it.
            var west = new Vector3(-11f, 1.7f, 6f);
            var near = Settle(provider, siren, west, AcousticConstants.GlobalRegionId);
            Report("outside, west of the doorway", near);

            // 2. The mirror image, to the EAST. Same distance, opposite side.
            var east = new Vector3(-3f, 1.7f, 6f);
            var mirrored = Settle(provider, siren, east, AcousticConstants.GlobalRegionId);
            Report("outside, east of the doorway", mirrored);

            // 4. Much further away, on the same bearing as the first.
            var far = new Vector3(-25f, 1.7f, -12f);
            var distant = Settle(provider, siren, far, AcousticConstants.GlobalRegionId);
            Report("outside, far away", distant);

            // 3. Standing in the room.
            var inside = Settle(provider, siren, RoomCentre with { Y = 1.7f }, RoomRegionId);
            Report("inside the room", inside);

            bool ok = true;
            ok &= Check("the doorway HRTF stage is engaged from outside", near.Localized);
            ok &= Check("the reverb bus is audible from outside", near.Volume > 0.01f);
            ok &= Check("the outside reverb reaches the ears unequally (it has a direction)",
                        Asymmetry(near) > 0.02f);
            ok &= Check("crossing to the other side of the doorway swaps which ear leads",
                        Math.Sign(near.RmsL - near.RmsR) != Math.Sign(mirrored.RmsL - mirrored.RmsR));
            // Measured energy, not the bookkeeping value: `busLevel` is what the gating rule COMPUTED,
            // and it computed the same numbers before the fix, when it was being applied to a fader the
            // sends had bypassed. What proves the fader is in the path is the level that came out of it.
            ok &= Check("the bus fader is in the signal path: distance lowers the measured level",
                        Energy(distant) < Energy(near) * 0.75f);
            ok &= Check("inside the room the reverb fills the space (HRTF stage bypassed)",
                        !inside.Localized);
            ok &= Check("inside the room the bus is at full level", inside.Volume > 0.9f);

            // 5. The crossing itself. A hard bypass toggle was a step change in the signal — one click
            // per threshold, and a stream of them while standing in the doorway. Walk in, and watch how
            // fast the localization can move between one audio update and the next.
            float worstJump = WalkThroughTheDoorway(provider, siren);
            Console.WriteLine($"  crossing the threshold             largest localization change in one update = {worstJump:F3}");
            ok &= Check("crossing the threshold ramps rather than snapping", worstJump < 0.25f);

            Console.WriteLine(ok
                ? "RESULT: PASS — a room's reverb is gated by its doorway and arrives from it."
                : "RESULT: FAIL — see the unmet conditions above.");
            return ok ? 0 : 1;
        }
        finally
        {
            provider.Dispose();
        }
    }

    private readonly record struct BusState(float Blend, float Volume, float RmsL, float RmsR)
    {
        public bool Localized => Blend > 0.5f;
    }

    /// <summary>Walks the listener from outside to the middle of the room and back, one small step per
    /// audio update, and returns the largest single-update change in the bus's doorway localization.
    /// A hard switch reports 1.0 — the whole range in one block.</summary>
    private static float WalkThroughTheDoorway(FmodAudioProvider provider, SpatialEmitter emitter)
    {
        var from = new Vector3(-7f, 1.7f, 4f);   // outside, square on to the opening
        var to = RoomCentre with { Y = 1.7f };   // the middle of the room
        float worst = 0f;
        float previous = float.NaN;

        for (int pass = 0; pass < 2; pass++)
        {
            for (int i = 0; i <= 120; i++)
            {
                float t = pass == 0 ? i / 120f : 1f - (i / 120f);
                Vector3 p = Vector3.Lerp(from, to, t);
                // The region the listener is in is what the game would report: inside once past the wall.
                int region = p.Z > Doorway.Z ? RoomRegionId : AcousticConstants.GlobalRegionId;

                provider.UpdateListener(p, Quaternion.Identity, Vector3.Zero, region);
                provider.UpdateSpatialAttributes(emitter);
                provider.Update();
                provider.TryGetReverbDiagnostics(RoomRegionId, out float blend, out _, out _, out _);

                if (!float.IsNaN(previous)) worst = Math.Max(worst, Math.Abs(blend - previous));
                previous = blend;
                Thread.Sleep(5);
            }
        }
        return worst;
    }

    private static float Energy(BusState s) => s.RmsL + s.RmsR;

    private static float Asymmetry(BusState s)
    {
        float sum = s.RmsL + s.RmsR;
        return sum <= 1e-6f ? 0f : Math.Abs(s.RmsL - s.RmsR) / sum;
    }

    /// <summary>Moves the listener and runs the provider until the bus volume lerp has settled
    /// (ReverbFadeSpeed is 0.15 per update) and the mixer has produced blocks to measure.</summary>
    private static BusState Settle(FmodAudioProvider provider, SpatialEmitter emitter,
                                   Vector3 listenerPos, int listenerRegionId)
    {
        for (int i = 0; i < 140; i++)
        {
            provider.UpdateListener(listenerPos, Quaternion.Identity, Vector3.Zero, listenerRegionId);
            provider.UpdateSpatialAttributes(emitter);
            provider.Update();
            Thread.Sleep(5);
        }

        // The tail is driven by noise, so a single mixer block is a poor measurement. Average over a
        // couple of hundred of them once the level has settled.
        float blend = 0f, vol = 0f;
        double sumL = 0, sumR = 0; int samples = 0;
        for (int i = 0; i < 120; i++)
        {
            provider.UpdateListener(listenerPos, Quaternion.Identity, Vector3.Zero, listenerRegionId);
            provider.UpdateSpatialAttributes(emitter);
            provider.Update();
            provider.TryGetReverbDiagnostics(RoomRegionId, out blend, out vol, out float l, out float r);
            sumL += l; sumR += r; samples++;
            Thread.Sleep(5);
        }

        return new BusState(blend, vol, (float)(sumL / samples), (float)(sumR / samples));
    }

    private static void Report(string where, BusState s) =>
        Console.WriteLine($"  {where,-32} doorwayBlend={s.Blend:F2} " +
                          $"busLevel={s.Volume:F3} L/R={s.RmsL:F6}/{s.RmsR:F6} asymmetry={Asymmetry(s):P0}");

    private static bool Check(string what, bool held)
    {
        Console.WriteLine($"  [{(held ? "PASS" : "FAIL")}] {what}");
        return held;
    }

    /// <summary>One concrete room with one doorway onto the outside — the west room of the shipped
    /// default map, which is where the problem was heard.</summary>
    private static AcousticMap BuildMap()
    {
        var map = new AcousticMap(new Vector3(100, 40, 100), new Vector3(-50, 0, -50))
        {
            GlobalEnvironmentId = AcousticConstants.GlobalRegionId
        };

        int concrete = AcousticRegistry.GetProperties("Concrete").ResonanceIndex;
        map.Regions[RoomRegionId] = new RegionComponent
        {
            FriendlyName = "Concrete Room",
            IsIndoor = true,
            RoomSize = new Vector3(10, 5, 10),
            ReverbTimeScale = 1.0f,
            Materials = new[] { concrete, concrete, concrete, concrete, concrete, concrete }
        };
        map.RegionPositions[RoomRegionId] = RoomCentre;
        map.RegionRotations[RoomRegionId] = Quaternion.Identity;

        map.Portals[1] = (new PortalComponent
        {
            RegionAId = AcousticConstants.GlobalRegionId,
            RegionBId = RoomRegionId,
            ApertureSize = 2.0f
        }, Doorway);

        return map;
    }
}
