<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenFPS.Common\OpenFPS.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="LiteNetLib" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />

    <PackageReference Include="System.Speech" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ASSETS\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="..\libs\*.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
