using System.Text.Json;
using Serilog;

namespace OpenFPS.Server.Repositories;

/// <summary>
/// Who owns each map, whether it is public, and who has been invited in: map_access.json, beside
/// teams.json and friends.json.
///
/// Kept apart from the map files on purpose. A map file is written by /savemap, which commits whatever
/// has been built; making a map private, or inviting somebody, must not commit half a house. And the
/// shipped maps are not ours to rewrite (city.json is generated by tools/gen_city.py). So the map file
/// says what the map is, and this says who may come in. At load it is laid over each map's own
/// OwnerId and IsPublic; a map it does not mention keeps what its file says.
///
/// Thread-safe for the same reason TeamRepository is: every write goes to disk under one lock.
/// </summary>
public class MapAccessRepository
{
    public sealed class Entry
    {
        public string Owner { get; set; } = "";
        public bool Public { get; set; } = true;
        public List<string> Invited { get; set; } = new();
        /// <summary>Who the owner has asked to edit the map with the world editor (/map editor add).</summary>
        public List<string> Editors { get; set; } = new();
    }

    private readonly string? _path;
    private readonly object _lock = new();
    private Dictionary<string, Entry> _maps = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>A null path keeps everything in memory (a test rig).</summary>
    public MapAccessRepository(string? path)
    {
        _path = path == null ? null : Path.GetFullPath(path);
        Load();
    }

    private void Load()
    {
        if (_path == null || !File.Exists(_path)) return;
        try
        {
            var loaded = JsonSerializer.Deserialize<Dictionary<string, Entry>>(File.ReadAllText(_path));
            if (loaded != null) _maps = new Dictionary<string, Entry>(loaded, StringComparer.OrdinalIgnoreCase);
        }
        catch (Exception ex)
        {
            // Kept aside rather than overwritten: a file that will not parse is somebody's invitations.
            Log.Error("MapAccessRepository: {Path} could not be read ({Error}); maps keep what their own files say.", _path, ex.Message);
            try { File.Copy(_path, _path + ".bad", overwrite: true); } catch { }
        }
    }

    private void Write()
    {
        if (_path == null) return;
        string json = JsonSerializer.Serialize(_maps, new JsonSerializerOptions { WriteIndented = true });
        string temp = _path + ".tmp";
        File.WriteAllText(temp, json);
        File.Move(temp, _path, overwrite: true);
    }

    /// <summary>Lays what is kept over a loaded map's own owner and public flag, and gives it its invitations.</summary>
    public void ApplyTo(MapData map)
    {
        lock (_lock)
        {
            if (!_maps.TryGetValue(map.Id, out var e)) return;
            map.OwnerId = e.Owner;
            map.IsPublic = e.Public;
            map.Invited = new List<string>(e.Invited);
            map.Editors = new List<string>(e.Editors ?? new List<string>());
        }
    }

    /// <summary>Records a map's owner, public flag and invitations as they now stand in memory.</summary>
    public void Record(MapData map)
    {
        lock (_lock)
        {
            _maps[map.Id] = new Entry
            {
                Owner = map.OwnerId ?? "", Public = map.IsPublic, Invited = new List<string>(map.Invited),
                Editors = new List<string>(map.Editors),
            };
            try { Write(); }
            catch (Exception ex) { Log.Error("MapAccessRepository: could not write {Path}: {Error}", _path, ex.Message); }
        }
    }
}
